---
framework: mocha
preRun:
     command:
        - npm install
        - npm run build
preMerge:
  pattern:
    - "./test/main/**/*.spec.js"
postMerge:
  pattern:
    - "./test/main/**/*.spec.js"
postRun:
     command:
        - node --version
configFile: mocharc.yml
version: 1.0
